### PR TITLE
Link to Japanese translation

### PR DESCRIPTION
**Pull request by eed3si9n**
Here's a link to Japanese translation.
日本語 is the endonym for Japanese language.

### CODE REVIEW

**Comment by ncase** [comment]
That was fast! Thank you so so much! 🎉

**Comment by eed3si9n** [comment]
@ncase Thanks for working on this awesome project!

I noticed that link back to English was removed in https://github.com/ncase/covid-19/commit/0fef2f40db343e4d9e3ffe5ae0ed2bc113349050.
The idea for English link was so the translators can copy-paste the section and we can cross-link among all the localized pages, like Wikipedia articles. If you prefer some other style of linking back to the original English page, please let me/us know.

**Comment by ncase** [comment]
Good point! By your suggestion, in https://github.com/ncase/covid-19/commit/190a3372aea9047490c73a590e37a020493ac5e5 I added:

```
<!-- IF YOU'RE MAKING A TRANSLATION, UN-COMMENT THE NEXT LINE -->
<!-- <li><a href='https://ncase.me/covid-19/'>English (original version)</a></li> -->
```

Hope that helps!

**Comment by eed3si9n** [comment]
Thanks!

**Pull request merged**
